[package]
name = "protonhaxora"
version = "0.5.2"
edition = "2021"

[dependencies]
slint = "1.3.2"
steamlocate = "2.0"
device_query = "2.1.0"
confy = "0.6.1"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
slint-build = "1.3.2"

[profile.release]
strip = true
opt-level = 3
