[package]
name = "protonhax-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.9", features = ["backend-qt"] }
steamlocate = "2.0.1"

[build-dependencies]
slint-build = "1.9"
